engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
    - "src/versions"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- "test"
- "**/*.spec.js"
- "**/*.spec.jsx"
